# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    router:
        strict_requirements: null
        default_uri: "http://localhost:8012"

    session:
        name: session_id

    rate_limiter:
        login_attempts:
            policy: 'fixed_window' #sliding_window
            limit: 5
            interval: '5 minutes'
            cache_pool: cache.rate_limiter
        forgot_password:
            policy: 'fixed_window'
            limit: 3
            interval: '1 minute'
            cache_pool: cache.rate_limiter

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
